### ISSUE TITLE
If all ralfs are dead, calls fail

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1103]
When all ralfs are dead, calls fail with a 408. SAS traces are available.

**Comment by dtheobald** [comment]
By "dead" I mean powered down.

**Comment by mirw** [comment]
OK, so the issue here is that we send requests to Ralf on the same thread as we process SIP requests (although we do it after we've completed processing the SIP request).  We do this synchronously, so if all Ralfs die we end up blocking threads.  This is made worse by https://github.com/Metaswitch/cpp-common/issues/132, which means that we take 1s to time out each Ralf (and we always try 2).  At a few calls per second, we'll have more SIP requests coming in than we have threads to process them.

I think the fix here is probably to make sending the ACR asynchronous.

**Comment by mirw** [comment]
Tagging as medium-priority because, while this is obviously bad behavior, it should be unusual for all Ralfs to fail.

**Comment by bossmc** [comment]
Ralf outages should never cause call failures, Rf billing is specified to be asynchronous for this very reason.  Raising priority (as even one failure could cost us 1 second in timeout which blows our latency targets).

**Comment by JimBunch** [comment]
Marking as critical since it is service affecting.

**Comment by eleanor-merry** [comment]
@dtheobald - can you please pull in this fix and retest?

**Comment by dtheobald** [comment]
Fixed
