### ISSUE TITLE
On call diversion, Sprout duplicates START ACRs (and doesn't send ENDs)

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#1199]
Run the "Call Diversion AS - Unconditional" clearwater-live-test.  Check the Rf flows.  Often (if not every time), you will see 4 Rf sessions being started(2 originating, 2 terminating) and only 2 being ended (1 originating, 1 terminating).

This actually appears to be due to the flows from Sprout to Ralf - Sprout seems to send multiple START ACRs for the same node type and role, and Ralf (slightly blindly) honors this, creating multiple Rf sessions.  When Sprout sends ENDs, Ralf only sends ENDs for a subset of the Rf sessions (as it only seems to expect to have one session per node type and role.

This issue exhibits with other call diversion scenarios too - the above is just the simplest.

**Comment by mirw** [comment]
@JimBunch, should this be `critical`?  I suspect so - this may result in incorrect billing records.

**Comment by JimBunch** [comment]
Marking as critical since it affects billing.

**Comment by bossmc** [comment]
What's happening is that we're creating a `RalfACR` at the start of `orig` processing and a second at the start of `term` processing for the originally dialled number (this is all business as usual).  Then, when the AS redirects the call, we create a new `RalfACR` for the new `cdiv-orig` scope and finally will go on to create one for the `term` processing for the final number.

The IMS specifications are unclear on where billing should be performed when ASs are involved in a call path and discuss nothing about what should happen on redirection.  It seems there are three sensible approaches:

* Only bill at `orig` and `term` for the finally set up call.
* Bill at `orig`, at every `orig-cdiv` and at the final `term`
* Bill at `orig`, at every `term`, at every `orig-cdiv` and at the final `term`

An important caveat is that in order to bill at a point in the call, we also need to Record-Route at that same point (so we can produce INTERIM ACRs and STOP ACRs).  With our current RR configuration options, the latter two options above require us to Record-Route between every AS invocation, which is not recommended behaviour in any deployment.  So, for now I will resolve this to only generate two billing records for diverted calls (regardless of how many diversions occur) and we can look at the bigger picture of how to align record-routing with billing as a scheduled enhancement.
