### ISSUE TITLE
enum.json is not reloaded by a 'service sprout reload'

### ISSUE THREAD

**Issue by steelyvoid** [Metaswitch/sprout#1209]
Unlike bgcf.json and s-cscf.json

This means that /usr/share/clearwater/clearwater-config-manager/scripts/upload_enum_json won't activate any new enum config uploaded (requires an explicit restart of sprout).

Presumably this is down to the fact that an Updater object (as created in scscfselector.cpp and bgcfservice.cpp to take care of s-cscf.json and bgcf.json uploads respectively) hasn't been created in enumservice.cpp

**Comment by Tom-Rees** [comment]
@bossmc ,
I think the right fix here is, as Steve says, to give JSONEnumService an update method and create a new Updater with this member function. The new function should be able to use the code currently in the constructor if I pull the relevant bits out into a private method. This should be transparent to existing code as it uses the EnumService parent class which won't have such a method defined.

Does that all sound sensible/correct to you?
(Apologies if you're the wrong person to ask about this)

Thanks,
Tom

**Comment by bossmc** [comment]
Yep, sounds right to me.  The one thing you might need to be careful of is how locking works during the update.  You'll probably need to wrap the `JSONENUMService` APIs in a read-write lock (if there's not already a lock there...) otherwise a service thread might try to do an ENUM lookup while we're loading the new JSON file (done in the updater thread) which sounds like a recipe for crashes.
