### ISSUE TITLE
Comm failure between geo sites causes persistent call failures

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1225]
During my tests I have one site (vm4) calling the other site (vm3) at 100% completion. I then cut communications between the two sites and start see calls failing. With log_level=5, the nearest I can tell is that sprout is failing the calls because of a failure retrieving data from memcached. Strangely, the errors seem to be caused by not being able to access the local (vm4) replicas.

The last set of failed calls originated from vm4 subscribers:
```
8645554101
8645554102
8645554103
8645554104
8645554105
```
Diags are available.

**Comment by JimBunch** [comment]
Marking as critical since it is service affecting.

**Comment by mirw** [comment]
I'll take a first look at this (and may pass it on once someone else has some bandwidth).

**Comment by mirw** [comment]
I've spent some time looking at this, but I'm not sure I really understand the scenario.

I think

*   you have 2 sites, vm4 and vm3, in a GR configuration
*   subscribers `864555xxxx` are registering via vm4 and subscribers `863555xxxx` are registering via vm3
*   you're cutting communication between the 2 sites
*   ...and then expecting calls to continue to succeed?

That doesn't make much sense to me, so I think I've misunderstood the test case.  Please can you elaborate?

**Comment by mirw** [comment]
Just to clarify, if subscribers `863555xxxx` started registering via vm4 after the communication was cut, calls should continue but, as it is, I'd just expect their registrations to time out after 5 minutes, at which point they'd be unregistered.  (Indeed, that's what the diagnostics show.)

**Comment by mirw** [comment]
@dtheobald, passing to you to clarify.

**Comment by dtheobald** [comment]
The communications failure I introduce is between the Clearwater nodes of the site, but does not include their Perimeta(s), so when vm4 tries to call vm3, it still has a path to vm3's Perimeta and should be able make calls to those subscribers (as it has in the past).

The problem I was seeing on vm4 was that vm4's sprout couldn't find the registration for vm4's subscribers (864555xxxx) because it couldn't lookup them up in memcached (which should've been local), so the calls failed.

**Comment by mirw** [comment]
Thanks for your clarification, but I think this testcase is based on a misunderstanding about how GR works.  Did this testcase pass in previous releases (and was it executed in exactly the same way)?

To recap, we have

*   Clearwater sites `vm4` and `vm3`, in a GR configuration
*   P-CSCFs associated with Clearwater sites `vm4` and `vm3`
*   subscribers `864555xxxx` registering via the P-CSCF for site `vm4` to Clearwater site `vm4`
*   subscribers `863555xxxx` registering via the P-CSCF for site `vm3` to Clearwater site `vm3`
*   registration expiry of 5 minutes
*   subscribers `864555xxxx` attempting calls to subscribers `863555xxxx`.

We then cut the link between Clearwater site `vm4` and Clearwater site `vm3`, but not the link between the P-CSCFs, or the link between the P-CSCFs and either Clearwater site - so both P-CSCFs can still talk to everything else.

The key point is what do the P-CSCFs do with the REGISTERs they receive?  From the diagnostics, I think the P-CSCFs are continuing to send REGISTERs to their associated Clearwater site, i.e. the P-CSCF for site `vm4` sends to Clearwater site `vm4` and likewise for `vm3`.  Since the sites are disconnected, and have no way of communicating, this means that, over the 5 minutes after the cut, all the registrations for subscribers `864555xxxx` in Clearwater site `vm3` expire (as they're no longer being refreshed) and all the registrations for subscribers `863555xxxx` in Clearwater site `vm4` expire (again, because they're not being refreshed).

What I'd expect to happen after the cut is

*   initially, all calls go through successfully - before the cut, both sites were replicating registrations to each other, so both sites know the location of all subscribers
*   for up to 5 minutes after the cut, some calls will continue to go through - these registrations have not yet expired
*   after 5 minutes, no calls between `864555xxxx` and `863555xxxx` will succeed
*   however, calls between `864555xxxx` and other `864555xxxx` numbers will still succeed, as will calls between `863555xxxx` and other `863555xxxx` numbers.

I think we generally wouldn't expect the type of network connectivity failure that you're testing - the link between the sites should be fault-tolerant, so this should be a double failure.  The more common scenario in which GR might be invoked is where a site is taken entirely offline, e.g. its power fails entirely, or the site is flooded (I know of customers from previous projects I've worked on who have suffered like this!).  In this case, we'd expect the P-CSCF associated with the failed site to route REGISTERs to the remaining site.  Even in the case where both the links between the Clearwater sites fail, it's possible to recover function by manually forcing the P-CSCF associated with one of the sites to route traffic to the other site.

Incidentally, I think you might be reading too much into the diagnostics.  You're right that Clearwater site `vm4` is trying to read from memcached instances in Clearwater site `vm3`, but this is only because it has determined there it knows of no registrations in Clearwater site `vm4` (see the logs a few lines above the logs about attempting to talk to site `vm3`).  To close up windows after GR recovery, a site that has no bindings for a subscriber falls back to attempting to read from the other site - this may fail (as it did here), but the call is going to fail anyway if we didn't try.

**Comment by dtheobald** [comment]
I haven't been able to reproduce the other anomaly often enough for further investigation, so I'm closing this issue.
