### ISSUE TITLE
sprout's init.d script no longer pulls in /etc/clearwater/user_settings

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1336]
I couldn't turn on sprout debug logs by changing log_level in user_settings and noticed that sprout's init.d script is no longer pulling in the user_settings.

**Comment by graemerobertson** [comment]
/etc/clearwater/user_settings should get pulled in by /etc/clearwater/config, which then gets pulled in to Sprout's init.d. What does your /etc/clearwater/config file look like?

**Comment by dtheobald** [comment]
My config doesn't do that since the node used have an older release installed. Is this a new approach to including user_settings? Homestead and ralf pull in user_settings in their respective init.d scripts like sprout used to in the last release.

**Comment by graemerobertson** [comment]
We've included user_settings through /etc/clearwater/config ever since we introduced local_config and shared_config I think, around last May. We stopped including user_settings from Sprout.init.d in November since it should be redundant, and we should do the same in Ralf/Homestead.

If you're upgrading a deployment from the era before /etc/clearwater/config was split into shared_config and local_config, you should follow the migration procedure here http://clearwater.readthedocs.org/en/latest/Migrating_To_etcd/index.html.

**Comment by dtheobald** [comment]
Okay. I'll make the adjustment
