### ISSUE TITLE
Nonce count processing is not backward compatible causing call failures during upgrade

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1405]
#### Symptoms

Earlier versions of sprout (e.g., release-82) accept re-registrations with nonce counts of any value. However, new sprouts (e.g. release-94 and later) reject those same re-registrations which cause backward compatibility problems during the upgrade process.

#### Impact

Re-registrations can fail causing some calls to fail.

#### Release and environment 

Upgrade from release-82 to release-94

#### Steps to reproduce
1) Launch release-82 system (2 homestead, 2 sprouts)
2) In preparation for upgrade, set ```impi_store_mode=av-impi``` in shared_config and distribute.
3) Run traffic (10 cps) on release-82 system with re-registrations and valid nonce counts
4) Upgrade homestead nodes.
5) Upgrade a sprout node
Re-registrations will intermittently fail (be challenged) depending on which sprout does the processing; which causes intermittent call failures (480 not found).

Diags have been collected.

**Comment by mirw** [comment]
Thanks for raising this!

Do you have SAS trace from failed registrations?

...and on the re-registrations with nonce counts of any value, are you saying that these *weren't* re-challenged on release-82?  (I believe they should have been.)

**Comment by dtheobald** [comment]
I too was surprised that the older release didn't challenge re-registrations. 

I've had to flush my SAS, so I'll run the scenario again and get you some SAS traces.

**Comment by dtheobald** [comment]
I've put a SAS trace (rereg-82.sas) of re-registrations on release-82 in the diags area. I'm still working on getting the other trace.

**Comment by dtheobald** [comment]
I've put another SAS trace (rereg-mixed.sas) of a re-reg involving a mixed set of sprouts (sprout-1=release-94, sprout-2=release-82) in the diags area.

**Comment by mirw** [comment]
@dtheobald, thanks!  It does look as though we're stricter than we were before - I'd argue we were bugged before, but we don't want to regress even so.

@AlexHockey, please can you take a look?

**Comment by AlexHockey** [comment]
I've looked at the trace and the client is re-registering every 30s. That's going to be important.

On release-84: when a client first registers, sprout generates a challenge, rejects the REGISTER with a 401, and stores the challenge in memcached for 40s (to give the client time to form their authentication response). When the authenticated REGISTER is received, sprout set a "tombstone" flag in the challenge and writes it back to memcached. Unfortunately the code is a bit loose and this write extends the lifetime of the challenge for another 40s. 

30s later a re-REGISTER is received. The challenge still exists in memcached at this point, and release-82 doesn't check the tombstone flag to see that the challenge had already been used. So sprout finds the challenge, allows the re-REGISTER, re-sets the tombstone flag and writes the challenge back to memcached, extending it lifetime for another 40s. Wash, rinse, repeat. 

The release-82 behavior has a nasty security hole. Consider this scenario:

* Alice (a genuine subscriber) registers with sprout (REGISTER, 401, REGISTER, 200). 
* Eve (an eavesdropper) observes this flow. 
* Eve replays the second REGISTER which is accepted by sprout (which has no policing of whether the challenge has previously been used). This also extends the challenge lifetime by 40s. 
* Eve can keep on re-REGISTERing every 30s by replaying the original REGISTER message. 

Release-94 fixes this hole. Regardless of whether nonce count support is enabled or not sprout would spot the replayed REGISTER and re-challenge it with a 401. I don't think we should re-introduce the hole just for backwards compatibility.

@dtheobald, can you modify the test script to re-REGISTER every minute rather than every 30s? With this change you should see the same behavior between releases 82 and 94. This will cause re-REGISTERs to be challenged with a 401, so you'll also need to make the test script expect this.

**Comment by dtheobald** [comment]
Yes, I'll give that a try.

**Comment by AlexHockey** [comment]
@nicolemcp a heads up: you might be interested in this issue as Clearwater's old behavior (release-82 and earlier) isn't great.

**Comment by dtheobald** [comment]
I have verified that increasing the re-reg interval to one minute makes release-82 challenge nonce counts > 1 (like release-94).

I'm going to try the upgrade process again with this in mind and let you know if I can get through it cleanly.

**Comment by dtheobald** [comment]
I've tried the upgrade again, but unfortunately it didn't go well. After upgrading the first homestead node to release-94 calls started failing because both the caller and callee ended up in the AUTH-PENDING state in the HSS; which persisted for 10+ minutes before I gave up waiting for it clear.

I must confess that I feel as if I'm doing something wrong, so I've repeated this scenario several times but got the same result each time.

I've gathered diags which you can find in the auth-pending directory.

**Comment by AlexHockey** [comment]
Right, I think I've figured out what's going on and its a bit complicated. 

The calls are failing because when Clearwater sends this LIR to the HSS:

```
00000000  LIR<REQ,PXY> ::= 
00000014  [ Session-Id = "homestead-2.x.dat.core.clearwater.metaswitch.com;1461177082;53" ]
0000005c  [ Vendor-Specific-Application-Id = 
00000064    [ Vendor-Id = 10415 ]
00000070    [ Auth-Application-Id = 16777216 ]
0000007c  ]
0000007c  [ Auth-Session-State = NO_STATE_MAINTAINED ]
00000088  [ Origin-Host = "homestead-2.x.dat.core.clearwater.metaswitch.com" ]
000000c0  [ Origin-Realm = "homestead.x.dat.core.clearwater.metaswitch.com" ]
000000f8  [ Destination-Realm = "x.shared.core.clearwater.metaswitch.com" ]
00000128  [ Public-Identity = "sip:3280000001@x.dat.core.clearwater.metaswitch.com" ]
```

the HSS sends back this LIA which is clearly bogus (for example, where is the response code?)

```
0000000  LIA<PXY> ::= 
00000014  [ Session-Id = "homestead-2.x.dat.core.clearwater.metaswitch.com;1461177082;53" ]
0000005c  [ Origin-Host = "hss.x.shared.core.clearwater.metaswitch.com" ]
00000090  [ Origin-Realm = "x.shared.core.clearwater.metaswitch.com" ]
000000c0  [ Auth-Session-State = NO_STATE_MAINTAINED ]
000000cc  [ Vendor-Specific-Application-Id = 
000000d4    [ Vendor-Id = 10415 ]
000000e0    [ Auth-Application-Id = 16777216 ]
000000ec  ]
```

I assume we're using OpenIMSCoreHSS here. In which case this is a known bug when the subscriber is in auth pending state (which Doug has correctly identified). The question then is why is the subscriber in the auth pending state in the first place. 

Looking at the last register before the failed call, Clearwater sends a MAR to the HSS but no SAR. If the subscriber is just re-registering, Clearwater will not send a SAR unless `hss_reregistration_time` seconds have passed since the last SAR it send for that subscriber. This time period defaults to 30 minutes. This is normally fine because the auth pending flag is only set in the HSS if it receives a MAR when the subscriber is not-registered but in this case Clearwater will always follow up with a SAR (which clears the auth pending flag).

Crucially, the last MAR before the failed call carried an S-CSCF server name of `sip:scscf.sprout.x.dat.core.clearwater.metaswitch.com:5054;transport=TCP`. This was sent after the homestead upgrade. The ones before the upgrade used `sip:sprout.x.dat.core.clearwater.metaswitch.com:5054;transport=TCP` I think this makes the HSS think that a new S-CSCF has been assigned, so goes back to treating the subscriber as not-registered. This means the lack of SAR leaves the subscriber in auth pending state. 

The fact that Clearwater changes its server name on upgrade is a known issue and @eleanor-merry owns fixing this.

@dtheobald if you wanted to, you could work around this issue in two ways:

Option 1: upgrade the HSS. The bad LIA it sends when in auth pending state is a bug that has been fixed. 

Option 2: tweak the config and scripts so that the test script only re-registers in the 2nd half of its registration period. 

* Set `req_max_expires=300` and `hss_reregistration_time=150` in shared config. 
* Configure the test script to re-register every 4 mins. 

The overall effect of option 2 is Clearwater will send a SAR to the HSS after 2.5 mins have passed since the last one. Since the subscriber is re-registering every 4 mins, every re-register will result in a SAR, and the subscriber will never get stuck in auth pending state.

**Comment by AlexHockey** [comment]
Assigning to Ellie to fix the server name bug.

**Comment by dtheobald** [comment]
Thanks @AlexHockey for the explanation. I went for option 1 and upgraded my HSS; which got me past this impasse.

**Comment by eleanor-merry** [comment]
@dtheobald sorry, I should have passed this back to you for retest
