### ISSUE TITLE
S-CSCF  does not add additional Record-Route headers when AS is invoked with sprout_rr_level=pcscf,icscf,as set in shared_config

### ISSUE THREAD

**Issue by salladi** [Metaswitch/sprout#1435]
#### Symptoms
With sprout_rr_level set to "pcscf,icscf,as" in the shared_config file made a call from a fixed line to a non-registered-PBX. Sprout adds just one Record-Route header for the Originating PCSCF handling but does not add Record_Route header for invoking application server when sending an INVITE to the application server.  Later on in the call setup Sprout adds two more Record-Route headers one for orginating ICSCF and one for terminating ICSCF but does not add one for invoking the AS when sending another INVITE to the AS. 
#### Impact
This fails one of the Clearwater Core test cases.

#### Steps to reproduce
Set sprout_rr_level=pcscf,icscf,as in /etc/clearwater/shared_config file. Make an IMS call involving an Application Server. Ceheck the INVITE messages at various stages of call set up,

Diags are available

**Comment by mirw** [comment]
@eleanor-merry, please can you take a look?

**Comment by graemerobertson** [comment]
I've taken a look at this, and I think this is working as designed. The reason we might want Sprout to record route between app server hops is for the scenario where Sprout invokes multiple app servers that record route themselves and that can't talk to each directly - i.e. if the Route set looked something like this, and appserver1 was unable to talk to appserver2:

```
Route: <sip:sprout@domain>
Route: <sip:appserver1@domain>
Route: <sip:appserver2@domain>
Route: <sip:sprout@domain>
```

Here we'd need Sprout to record route itself in between the app servers in order to act as a bridge between the two app servers.

@salladi, in your scenario, this is not the case. Why do you think there is a problem here? If the impact is literally that one of your test cases is failing, then I think the test case is probably wrong.

**Comment by graemerobertson** [comment]
We think that there were some misleading requirements here, but importantly, Sprout isn't doing anything wrong.
