### ISSUE TITLE
Zoiper client sometimes fails to register subscribers

### ISSUE THREAD

**Issue by AME2** [Metaswitch/sprout#1567]
#### Symptoms
When I was testing the release my Zoiper client often struggled with registering subscribers against both the dogfood system and the VMWare system. It failed to register approximately 50% of subscribers.

#### Impact
This made testing live calls more difficult.

#### Release and environment 
The subscribers were created using a recently upgraded VMWare and dogfood deployment.

#### Steps to reproduce
Provision a couple of subscribers using the VMWare's and dogfood's Ellis webUI. Attempt to register these with Zoiper (remember to add the authentication name as Zoiper does not do this automatically).

The SAS trace that I've uploaded seems to suggest that Zoiper never receives the 401 challenge from Sprout and Zoiper keeps sending reREGISTERs without a challenge response.
[Zoiper fail.zip](https://github.com/Metaswitch/sprout/files/538395/Zoiper.fail.zip)

**Comment by richardwhiuk** [comment]
What's happening here is that the request is sent by Zoiper on 172.18.42.16:52780, and is then NATed to being from 192.91.191.29:60437.

The response is then sent back to 192.91.191.29:52780. 

Zoiper isn't setting the "rport" option (which is defined per RFC 3581 - https://www.ietf.org/rfc/rfc3581.txt) which means this is the correct behaviour. This is required in order to work behind a NAT. We should update the documentation to note this.
