### ISSUE TITLE
poll_sprout_http is too aggressive

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/sprout#1570]
#### Symptoms

When running medium stress through Sprout I found that Sprout was being killed by poll_sprout_http failing (so monit sends an abort to Sprout) reasonably frequently (every half hour or so). It can also take more than 20 seconds for the poll_sprout_http script to start passing on start up, so this can lead to Sprout being killed multiple times in quick succession.
#### Impact

Sprout isn't stable at even medium stress. To work around this, I unmonitored the poll_sprout_http script.
#### Release and environment

From at least the Onix release

**Comment by johadalin** [comment]
@eleanor-merry I have a couple of questions on this.

* The PRs above should fix any occurrence of being killed due to overload, but you also mention it taking more than 2 polling cycles to start passing; should we be addressing the monit scripts to resolve this?

* What setup did you have when this issue was visible? Before closing this issue, it would be good to test the same setup and see if the problem persists at all.

**Comment by johadalin** [comment]
Discussed the concerns above, and agreed that closing this issue makes sense. 
The fix has been tested in isolation, and we are fairly certain that the original problem seen in this issue will be resolved by this change, so any new errors will be raised as separate issues. 
The Monit concern will also be raised separately if investigation shows it to be a true issue.
