### ISSUE TITLE
'Warning scscfsproutlet.cpp:1856: No charging role in Route header, assume originating' when using a sprout_rr_level other than the default

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1667]
#### Symptoms

I saw the following log on every SIP request while running stress:

```
04-01-2017 17:32:29.754 UTC Warning scscfsproutlet.cpp:1856: No charging role in Route header, assume originating
04-01-2017 17:32:29.926 UTC Warning scscfsproutlet.cpp:1856: No charging role in Route header, assume originating
04-01-2017 17:32:29.927 UTC Warning scscfsproutlet.cpp:1856: No charging role in Route header, assume originating
04-01-2017 17:32:30.441 UTC Warning scscfsproutlet.cpp:1856: No charging role in Route header, assume originating
```

Looking at the Route headers for an in-dialog request, they look like this:

```
Route:  <sip:scscf.sprout.stress.clearwater.test;transport=TCP;lr;service=scscf;billing-role=charge-orig>, <sip:mangelwurzel.infra.clearwater.test:5060;transport=TCp;lr;dialog>, <sip:scscf.sprout.stress.clearwater.test;transport=TCP;lr;service=scscf>, <sip:scscf.sprout.stress.clearwater.test;transport=TCP;lr;service=scscf>, <sip:mangelwurzel.infra.clearwater.test:5060;transport=TCp;lr;dialog>, <sip:scscf.sprout.stress.clearwater.test;transport=TCP;lr;service=scscf;billing-role=charge-term>,<sip:10.225.166.12:5082;transport=TCP;lr>
```

Specifically, the Route headers added at the end of originating processing and at the start of terminating processing don't have a billing-role parameter, causing this error. 

#### Impact

This causes log spam at the rate of 115 bytes per in-dialog message, which will increase the size/unwieldiness of diagnostics packages, unnecessarily worry users who see it, and make it harder to spot genuine errors.

This will also presumably cause billing information to be wrong, as when the S-CSCF is invoked before a terminating AS, it will assume its billing role is originating.

#### Release and environment 

10.0.0-161216-~255.00.0-161216.020317

I have `sprout_rr_level=pcscf,icscf,as` set for this testing, in order to test the supported features that are most likely to impact performance.

#### Steps to reproduce

Set `sprout_rr_level=pcscf,icscf,as` in `shared_config`, make a call, and check the log files.

**Comment by sebrexmetaswitch** [comment]
Removing my assignment to let someone else pick it up if they get a chance before I can look at it

**Comment by MatMeredith** [comment]
@bossmc Hi Andy, I think this issue was probably introduced by your changes in https://github.com/Metaswitch/sprout/pull/1212 to fix https://github.com/Metaswitch/sprout/issues/1199?   Any view on what the right fix is here?  I know that this was a while ago, but anything useful you can remember would be appreciated!

**Comment by MatMeredith** [comment]
So...

Route:  
<sip:scscf.sprout.stress.clearwater.test;transport=TCP;lr;service=scscf;billing-role=charge-orig>, 
<sip:mangelwurzel.infra.clearwater.test:5060;transport=TCp;lr;dialog>, 
<sip:scscf.sprout.stress.clearwater.test;transport=TCP;lr;service=scscf>, 
<sip:scscf.sprout.stress.clearwater.test;transport=TCP;lr;service=scscf>, 
<sip:mangelwurzel.infra.clearwater.test:5060;transport=TCp;lr;dialog>, 
<sip:scscf.sprout.stress.clearwater.test;transport=TCP;lr;service=scscf;billing-role=charge-term>,<sip:10.225.166.12:5082;transport=TCP;lr>

Sprout is deliberately and correctly only adding billing-roles to the first and last routes here because these are the only legs that we should be generating billing records for.

The log that Rob highlights is caused by the fact that we are trying to create an ACR for the other legs and there is no billing-role.   If we do indeed go on to generate billing records for these legs then the role will be wrong on some of them.

Discussed with @bossmc who wrote this function and we think that the right fix here is to introduce another value of billing-role "none" (billing-role is just something that we've invented so that's fine).    Then when we go to create the ACR for a request...
- Log as we do currently if there is no billing-role specified
- Don't create the ACR if the billing role is None

We should also check (before fixing this) that we have UTs that verify what billing records get generated for a call where we have both incoming and terminating ASs and we are record-routing every hop.   (I.e. that repro this scenario).

**Comment by MatMeredith** [comment]
Fixed by https://github.com/Metaswitch/sprout/pull/1716

**Comment by rkd-msw** [comment]
Confirmed that I'm not seeing this log - I'm happy that your live testing of the billing issue is good enough for now.
