### ISSUE TITLE
When GR Clearwater site fails, INVITEs to that site's P-CSCF don't get routed to the correct S-CSCF

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#905]
I have two GR Clearwater sites (VM3, VM4). If I take down the Clearwater portion of the site (e.g. VM4), REGISTERs get routed to the correct I-CSCF on VM3. However, subsequent INVITEs don’t get routed to the correct S-CSCF (by the P-CSCF[Perimeta]) because the Service-Route (on the REGISTER’s 200 OK) contains Sprout’s port number (5054) even though the I-CSCF determined the S-CSCF’s port via SRV record lookup. As such, the P-CSCF[Perimeta] doesn’t look up SRV records for Sprout when it receives an INVITE from the UE that contains Route header to Sprout containing a port number (5054). In the end all calls going through the down Clearwater site’s P-CSCF[Perimeta] fail.

In the diags area you’ll find three SAS traces:

* vm4-term-reg-on-vm3.sas – Terminator’s registration that would normally be handled by VM4 is routed to VM3 because VM4 is down.
* vm4-term-reg-on-vm4.sas – Terminator’s registration as seen by VM4’s P-CSCF.
* invite-to-vm4-proxy.sas – INVITE to the above terminator.

**Comment by dtheobald** [comment]
I have made adjustments to my Abucus and made sure that it is not contributing to Perimeta’s use of port 5054 when sending INVITEs to Sprout (see INVITE SAS trace in the diags). However, in diag file vm3-4.sas you’ll see that the 200 OK’s Service-Route field contains port number 5054 even though the selected S-CSCF URI (per homestead) does not contain a port number (see diag file vm4-2.sas) and as such sprout looks up SRV record _sip._tcp.sprout.mvoip.richlab.datcon.co.uk. Also, in diag file vm3-2.sas, you’ll see that the 200 OK sent to Perimeta contains a Service-Route containing a port number, which I presume Perimeta remembers and uses when processing INVITEs thereby preventing it from performing an SRV lookup and using VM4 sprouts instead of VM3 sprouts (which are down).

**Comment by rkd-msw** [comment]
The Service-Route header is determined by the scscf_uri setting in /etc/clearwater/config on the Sprout node - can you confirm what that's set to? (It defaults to having port 5054 in unless explicitly set otherwise, so that it works out of the box in deployments without DNS-SRV).

**Comment by dtheobald** [comment]
I got it to work by setting sprout's scscf_uri without a port number (per Rob's suggestion). However, it doesn't see quite right that this configuration setting should override the preferred S-CSCF URI supplied by homestead (possibly as configured in an HSS). At a minimum it's confusing, at least it was to me since my homestead was providing sprout with an non-port qualified S-CSCF URI.

**Comment by rkd-msw** [comment]
I think the two things are actually separate:
* the URI that Homestead provides is to Sprout acting as an I-CSCF - it defines which S-CSCF Sprout should route to
* the URI in scscf_uri is for Sprout acting in its role as an S-CSCF - it defines how the S-CSCF should identify itself to other nodes

I agree that this situation is confusing, but I think that's a result of having inconsistent configuration in the network (one form of URI used in Sprout's /etc/clearwater/config, and another at Homestead/the HSS). If Sprout put the URI it received from Homestead in the Service-Route, I think there's a possible situation where Sprout's scscf_uri setting was correctly configured, but not being used - which feels equally confusing.

(Additionally, I think if the Sprout I-CSCF and S-CSCF nodes were separated, you couldn't do this easily - because the S-CSCF node that creates the Service-Route wouldn't necessarily see the URI information that Homestead passed back to the I-CSCF node.)

Are you happy to close this, or do you think there's something more we should be doing here?

**Comment by dtheobald** [comment]
I happy to close it.
