### ISSUE TITLE
Call traffic impacted when a Ralf is isolated from the network

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/sprout#920]
While running 2 CPS traffic on a duplex Clearwater configuration, Ralf-1 was isolated from the network (port disconnected from vSwitch). Calls start failing mostly with 503 Service Unavailable errors. SAS logs indicate that most of these are caused by overload controls. Shortly after the Ralf node is isolated, both Sprouts are restarted by Monit due to heartbeat errors. Call errors persist as long as Ralf-1 remains isolated from the network.
	
The same behaviour is also observed if Ralf-1 is simply powered off as well.

**Comment by bossmc** [comment]
Ok, the provided SAS logs only indicate that SIP work is being rejected due to overload, I can't see any SAS logs that cover SIP processing that makes it past the overload protection.  If you can gather one of these it would be very useful (if only to confirm my later assertions).

Looking at the Sprout logs, it looks like we're timing out the connection to the Ralf (which is expected, without the Ralf node there to send back ICMP Unreachable messages, the TCP SYNs will eventually time out), there are many issues occurring here at once:

1. We appear to be timing out connections to both Ralf nodes (not just the segregated one), quote from the logs:

        22-01-2015 16:31:42.923 UTC Error httpconnection.cpp:573: http://ralf.vm1.richlab.datcon.co.uk:10888/call-id/0gQAAC8WAAACBAAALxYAABanrasmpL4YeENxlth%2B7%2FMZ5ozGGu0W%2FdWsUMkcoHgcqHnMtzRUPj%2FczZzPC4MUxOAACjhMgJ2Q86fgTpGh6jJBfgj5tw0fqqyESMl6ZbCT%40192.168.140.215 failed at server 192.168.140.202 : Timeout was reached (28) : fatal
        22-01-2015 16:31:43.925 UTC Error httpconnection.cpp:573: http://ralf.vm1.richlab.datcon.co.uk:10888/call-id/0gQAAC8WAAACBAAALxYAABanrasmpL4YeENxlth%2B7%2FMZ5ozGGu0W%2FdWsUMkcoHgcqHnMtzRUPj%2FczZzPC4MUxOAACjhMgJ2Q86fgTpGh6jJBfgj5tw0fqqyESMl6ZbCT%40192.168.140.215 failed at server 192.168.140.203 : Timeout was reached (28) : fatal

2. I can't tell from the logs, but we should have blacklisted the broken Ralf quickly and stopped trying to connect to it.  If the other Ralf is also unreachable, we'll end up black-listing them both then attempting to connect to them both anyway (the blacklist is really a grey-list).  It seems likely this has happened given the log files.

3. We are attempting these connections on the same threads that are used to process SIP requests and the time this takes (1 second due to https://github.com/Metaswitch/cpp-common/issues/132) is counted towards our latency calculations.  Leading to the aggressive overload behaviour:

        Target latency: 100000us
        Current latency: 399478us
        Requests limited to a rate of 1.1686829192468974e-42/sec

4. Related to (3), we probably should never allow our rate limiting to drop as low as `1e-42/sec` (which is one request per 1e24 universe lifetimes).  We'll never recover from a rate limit that low (as we need some requests to succeed to report lower latencies to increase the rate).

**Comment by bossmc** [comment]
Discussing with @plfrancis suggests that the second Ralf being unreachable is unexpected given the test set-up, it looks like there might be a Ralf issue with losing connection to one of the other Ralfs (either in memcached or chronos with memcached being the current best guess).

@plfrancis can you gather level 5 logs from the Sprout nodes and the non-segregated Ralf node please?

**Comment by bossmc** [comment]
The SAS logs are misleading (see https://github.com/Metaswitch/sas-client/issues/45) so we can ignore point 4 (and I'll look at the debug logs to see if point 3 is still an issue too).

**Comment by mirw** [comment]
@plfrancis, I believe this is with you to confirm if there are remaining issues open here.

**Comment by bossmc** [comment]
The underlying issue was Memcached timing out requests to the unreachable node.  This was resolved in https://github.com/Metaswitch/cpp-common/pull/240.  The SAS issue is covered by https://github.com/Metaswitch/sas-client/issues/45 and a temporary fix was added in https://github.com/Metaswitch/clearwater-sas-resources/pull/60.
