### ISSUE TITLE
Mass confusion on I-CSCF if `scscf_uri` isn't `sip:sprout.<home domain>`

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#929]
The SproutletProxy class has a `root_uri` field.  This is used to decide whether a URI is local, and so should invoke sproutlets.  For example, `sip:bgcf.<root uri host>` will invoke BGCF function.  Currently the root URI is set to the `scscf_uri` configuration option in `/etc/clearwater/config`.

This seems wrong on an I-CSCF but as long as the scscf_uri is always `sip:sprout.<home domain>` (modulo transport and port), this works, because it matches what the I-CSCF expects anyway.  If the `scscf_uri` option is set to something else, it will probably break, or at least be very confusing.

I suspect we should fix both I-CSCF and S-CSCF to use the local cluster name rather than the `scscf_uri`.  Failing that, we should use `icscf_uri` on I-CSCFs (although this isn't generally set).

**Comment by rkd-msw** [comment]
Per https://github.com/Metaswitch/clearwater-docs/wiki/Clearwater-Configuration-Options-Reference, `icscf_uri` is "the SIP address of the external I-CSCF integrated with your Sprout node (if you have one)". It's not the identity of the Sprout I-CSCF (so we shouldn't use it here).

This is different from `scscf_uri`, which is the identity of the Sprout S-CSCF - that's because:

* the S-CSCF needs to know its own identity (for the Diameter Server-Name AVP and the Service-Route header), whereas the I-CSCF doesn't
* the I-CSCF learns the URIs of its S-CSCFs from s-cscf.json, so doesn't need to use the `scscf_uri` config option - the S-CSCF doesn't have an equivalent file, so needs the `icscf_uri` to know where to route terminating requests.

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/sprout/pull/1364
